controller_list:
  - name: fake_iiwa_green_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_green_joint_1
      - iiwa_green_joint_2
      - iiwa_green_joint_3
      - iiwa_green_joint_4
      - iiwa_green_joint_5
      - iiwa_green_joint_6
      - iiwa_green_joint_7
  - name: fake_iiwa_blue_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_blue_joint_1
      - iiwa_blue_joint_2
      - iiwa_blue_joint_3
      - iiwa_blue_joint_4
      - iiwa_blue_joint_5
      - iiwa_blue_joint_6
      - iiwa_blue_joint_7
initial:  # Define initial robot poses per group
  - group: iiwa_green_arm
    pose: home
  - group: iiwa_blue_arm
    pose: home