iiwa_green_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - iiwa_green_joint_1
    - iiwa_green_joint_2
    - iiwa_green_joint_3
    - iiwa_green_joint_4
    - iiwa_green_joint_5
    - iiwa_green_joint_6
    - iiwa_green_joint_7
  gains:
    iiwa_green_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_green_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_green_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_green_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_green_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_green_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_green_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
iiwa_blue_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - iiwa_blue_joint_1
    - iiwa_blue_joint_2
    - iiwa_blue_joint_3
    - iiwa_blue_joint_4
    - iiwa_blue_joint_5
    - iiwa_blue_joint_6
    - iiwa_blue_joint_7
  gains:
    iiwa_blue_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_blue_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_blue_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_blue_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_blue_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_blue_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_blue_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1