controller_list:
  - name: iiwa_green_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - iiwa_green_joint_1
      - iiwa_green_joint_2
      - iiwa_green_joint_3
      - iiwa_green_joint_4
      - iiwa_green_joint_5
      - iiwa_green_joint_6
      - iiwa_green_joint_7
  - name: iiwa_blue_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - iiwa_blue_joint_1
      - iiwa_blue_joint_2
      - iiwa_blue_joint_3
      - iiwa_blue_joint_4
      - iiwa_blue_joint_5
      - iiwa_blue_joint_6
      - iiwa_blue_joint_7